/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BankDetail {
    id: bigint;
    ifscCode: string;
    name: string;
    district: string;
    taluka: string;
}
export interface Account {
    id: bigint;
    studentId: bigint;
    ifscCode: string;
    bankId: bigint;
    initialAmount: bigint;
    accountNumber: string;
}
export interface Transaction {
    id: bigint;
    transactionType: Variant_deposit_withdrawal;
    accountId: bigint;
    date: Time;
    totalAmount: bigint;
    amount: bigint;
    reason: string;
}
export type Time = bigint;
export interface UserProfile {
    name: string;
    accountNumber: string;
}
export interface Student {
    id: bigint;
    dob: Time;
    attendanceNumber: bigint;
    name: string;
    district: string;
    taluka: string;
    studentClass: string;
    schoolName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_deposit_withdrawal {
    deposit = "deposit",
    withdrawal = "withdrawal"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAccount(studentId: bigint, bankId: bigint, accountNumber: string, initialAmount: bigint, ifscCode: string): Promise<bigint>;
    addBankDetail(name: string, taluka: string, district: string, ifscCode: string): Promise<bigint>;
    addStudent(name: string, dob: Time, studentClass: string, attendanceNumber: bigint, schoolName: string, taluka: string, district: string): Promise<bigint>;
    addTransaction(accountId: bigint, date: Time, transactionType: Variant_deposit_withdrawal, amount: bigint, reason: string, totalAmount: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAccount(accountId: bigint): Promise<boolean>;
    deleteBankDetail(bankDetailId: bigint): Promise<boolean>;
    deleteStudent(studentId: bigint): Promise<boolean>;
    deleteTransaction(transactionId: bigint): Promise<boolean>;
    getAccountById(accountId: bigint): Promise<Account | null>;
    getAllAccounts(): Promise<Array<Account>>;
    getAllBankDetails(): Promise<Array<BankDetail>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBankDetailById(bankDetailId: bigint): Promise<BankDetail | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPassbook(accountNumber: string): Promise<{
        bankDetail?: BankDetail;
        account?: Account;
        student?: Student;
        transactions: Array<Transaction>;
    }>;
    getStudentById(studentId: bigint): Promise<Student | null>;
    getTransactionById(transactionId: bigint): Promise<Transaction | null>;
    getTransactionHistory(accountNumber: string, dateFrom: Time, dateTo: Time): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAccount(accountId: bigint, studentId: bigint, bankId: bigint, accountNumber: string, initialAmount: bigint, ifscCode: string): Promise<boolean>;
    updateBankDetail(bankDetailId: bigint, name: string, taluka: string, district: string, ifscCode: string): Promise<boolean>;
    updateStudent(studentId: bigint, name: string, dob: Time, studentClass: string, attendanceNumber: bigint, schoolName: string, taluka: string, district: string): Promise<boolean>;
    updateTransaction(transactionId: bigint, accountId: bigint, date: Time, transactionType: Variant_deposit_withdrawal, amount: bigint, reason: string, totalAmount: bigint): Promise<boolean>;
}
import type { Account as _Account, BankDetail as _BankDetail, Student as _Student, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAccount(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addBankDetail(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankDetail(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankDetail(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addStudent(arg0: string, arg1: Time, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addTransaction(arg0: bigint, arg1: Time, arg2: Variant_deposit_withdrawal, arg3: bigint, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAccount(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async deleteBankDetail(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBankDetail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBankDetail(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAccountById(arg0: bigint): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountById(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountById(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccounts();
            return result;
        }
    }
    async getAllBankDetails(): Promise<Array<BankDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankDetails();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankDetailById(arg0: bigint): Promise<BankDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankDetailById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankDetailById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassbook(arg0: string): Promise<{
        bankDetail?: BankDetail;
        account?: Account;
        student?: Student;
        transactions: Array<Transaction>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassbook(arg0);
                return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassbook(arg0);
            return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentById(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionById(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: string, arg1: Time, arg2: Time): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0, arg1, arg2);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0, arg1, arg2);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAccount(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateBankDetail(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBankDetail(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBankDetail(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: string, arg2: Time, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: bigint, arg2: Time, arg3: Variant_deposit_withdrawal, arg4: bigint, arg5: string, arg6: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_Transaction_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankDetail]): BankDetail | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankDetail: [] | [_BankDetail];
    account: [] | [_Account];
    student: [] | [_Student];
    transactions: Array<_Transaction>;
}): {
    bankDetail?: BankDetail;
    account?: Account;
    student?: Student;
    transactions: Array<Transaction>;
} {
    return {
        bankDetail: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.bankDetail)),
        account: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.account)),
        student: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.student)),
        transactions: from_candid_vec_n5(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: {
        deposit: null;
    } | {
        withdrawal: null;
    };
    accountId: bigint;
    date: _Time;
    totalAmount: bigint;
    amount: bigint;
    reason: string;
}): {
    id: bigint;
    transactionType: Variant_deposit_withdrawal;
    accountId: bigint;
    date: Time;
    totalAmount: bigint;
    amount: bigint;
    reason: string;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n8(_uploadFile, _downloadFile, value.transactionType),
        accountId: value.accountId,
        date: value.date,
        totalAmount: value.totalAmount,
        amount: value.amount,
        reason: value.reason
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
}): Variant_deposit_withdrawal {
    return "deposit" in value ? Variant_deposit_withdrawal.deposit : "withdrawal" in value ? Variant_deposit_withdrawal.withdrawal : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_deposit_withdrawal): {
    deposit: null;
} | {
    withdrawal: null;
} {
    return value == Variant_deposit_withdrawal.deposit ? {
        deposit: null
    } : value == Variant_deposit_withdrawal.withdrawal ? {
        withdrawal: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
