/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : bigint,
  'studentId' : bigint,
  'ifscCode' : string,
  'bankId' : bigint,
  'initialAmount' : bigint,
  'accountNumber' : string,
}
export interface BankDetail {
  'id' : bigint,
  'ifscCode' : string,
  'name' : string,
  'district' : string,
  'taluka' : string,
}
export interface Student {
  'id' : bigint,
  'dob' : Time,
  'attendanceNumber' : bigint,
  'name' : string,
  'district' : string,
  'taluka' : string,
  'studentClass' : string,
  'schoolName' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : { 'deposit' : null } |
    { 'withdrawal' : null },
  'accountId' : bigint,
  'date' : Time,
  'totalAmount' : bigint,
  'amount' : bigint,
  'reason' : string,
}
export interface UserProfile { 'name' : string, 'accountNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<[bigint, bigint, string, bigint, string], bigint>,
  'addBankDetail' : ActorMethod<[string, string, string, string], bigint>,
  'addStudent' : ActorMethod<
    [string, Time, string, bigint, string, string, string],
    bigint
  >,
  'addTransaction' : ActorMethod<
    [
      bigint,
      Time,
      { 'deposit' : null } |
        { 'withdrawal' : null },
      bigint,
      string,
      bigint,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[bigint], boolean>,
  'deleteBankDetail' : ActorMethod<[bigint], boolean>,
  'deleteStudent' : ActorMethod<[bigint], boolean>,
  'deleteTransaction' : ActorMethod<[bigint], boolean>,
  'getAccountById' : ActorMethod<[bigint], [] | [Account]>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBankDetails' : ActorMethod<[], Array<BankDetail>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBankDetailById' : ActorMethod<[bigint], [] | [BankDetail]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPassbook' : ActorMethod<
    [string],
    {
      'bankDetail' : [] | [BankDetail],
      'account' : [] | [Account],
      'student' : [] | [Student],
      'transactions' : Array<Transaction>,
    }
  >,
  'getStudentById' : ActorMethod<[bigint], [] | [Student]>,
  'getTransactionById' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionHistory' : ActorMethod<
    [string, Time, Time],
    Array<Transaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAccount' : ActorMethod<
    [bigint, bigint, bigint, string, bigint, string],
    boolean
  >,
  'updateBankDetail' : ActorMethod<
    [bigint, string, string, string, string],
    boolean
  >,
  'updateStudent' : ActorMethod<
    [bigint, string, Time, string, bigint, string, string, string],
    boolean
  >,
  'updateTransaction' : ActorMethod<
    [
      bigint,
      bigint,
      Time,
      { 'deposit' : null } |
        { 'withdrawal' : null },
      bigint,
      string,
      bigint,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];