/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'ifscCode' : IDL.Text,
  'bankId' : IDL.Nat,
  'initialAmount' : IDL.Int,
  'accountNumber' : IDL.Text,
});
export const BankDetail = IDL.Record({
  'id' : IDL.Nat,
  'ifscCode' : IDL.Text,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'taluka' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'dob' : Time,
  'attendanceNumber' : IDL.Nat,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'taluka' : IDL.Text,
  'studentClass' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  }),
  'accountId' : IDL.Nat,
  'date' : Time,
  'totalAmount' : IDL.Int,
  'amount' : IDL.Int,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addBankDetail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addStudent' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
        IDL.Int,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteBankDetail' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBankDetailById' : IDL.Func([IDL.Nat], [IDL.Opt(BankDetail)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPassbook' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'bankDetail' : IDL.Opt(BankDetail),
          'account' : IDL.Opt(Account),
          'student' : IDL.Opt(Student),
          'transactions' : IDL.Vec(Transaction),
        }),
      ],
      ['query'],
    ),
  'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getTransactionById' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Text, Time, Time],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateBankDetail' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
        IDL.Int,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'ifscCode' : IDL.Text,
    'bankId' : IDL.Nat,
    'initialAmount' : IDL.Int,
    'accountNumber' : IDL.Text,
  });
  const BankDetail = IDL.Record({
    'id' : IDL.Nat,
    'ifscCode' : IDL.Text,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'taluka' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'dob' : Time,
    'attendanceNumber' : IDL.Nat,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'taluka' : IDL.Text,
    'studentClass' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Variant({
      'deposit' : IDL.Null,
      'withdrawal' : IDL.Null,
    }),
    'accountId' : IDL.Nat,
    'date' : Time,
    'totalAmount' : IDL.Int,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addBankDetail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
          IDL.Int,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteBankDetail' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBankDetailById' : IDL.Func([IDL.Nat], [IDL.Opt(BankDetail)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPassbook' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'bankDetail' : IDL.Opt(BankDetail),
            'account' : IDL.Opt(Account),
            'student' : IDL.Opt(Student),
            'transactions' : IDL.Vec(Transaction),
          }),
        ],
        ['query'],
      ),
    'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getTransactionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Text, Time, Time],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAccount' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateBankDetail' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
          IDL.Int,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };